# Generated by Django 5.2.7 on 2025-11-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='保单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('policy_type', models.CharField(max_length=50, verbose_name='保险类型')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保费')),
                ('start_date', models.DateField(verbose_name='起始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保险策略',
                'verbose_name_plural': '保险策略',
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
