# Generated by Django 5.2.7 on 2025-11-02 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.FileField(upload_to='plan_documents/', verbose_name='文件路径')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('insured_name', models.CharField(blank=True, max_length=100, verbose_name='受保人姓名')),
                ('insured_age', models.IntegerField(blank=True, null=True, verbose_name='受保人年龄')),
                ('insured_gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('insurance_product', models.CharField(blank=True, max_length=200, verbose_name='保险产品')),
                ('insurance_company', models.CharField(blank=True, max_length=200, verbose_name='保险公司')),
                ('annual_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='年缴保费')),
                ('payment_years', models.IntegerField(blank=True, null=True, verbose_name='缴费年数')),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总保费')),
                ('insurance_period', models.CharField(blank=True, max_length=50, verbose_name='保险期限')),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='基本保额')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='提取的完整数据')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '计划书文档',
                'verbose_name_plural': '计划书文档',
                'db_table': 'plan_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnualValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_year', models.IntegerField(verbose_name='保单年度终结')),
                ('guaranteed_cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='保证现金价值')),
                ('non_guaranteed_cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='非保证现金价值')),
                ('total_cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总现金价值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plan_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_values', to='api.plandocument', verbose_name='计划书')),
            ],
            options={
                'verbose_name': '年度价值',
                'verbose_name_plural': '年度价值',
                'db_table': 'annual_values',
                'ordering': ['plan_document', 'policy_year'],
                'unique_together': {('plan_document', 'policy_year')},
            },
        ),
    ]
