# Generated by Django 5.2.7 on 2025-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plandocument_annualvalue'),
    ]

    operations = [
        # content字段已存在，只添加table字段
        migrations.AddField(
            model_name='plandocument',
            name='table',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='年度价值表'),
        ),
    ]
