# Generated by Django 5.2.7 on 2025-11-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plandocument_content_plandocument_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='annual_premium',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='年缴保费'),
        ),
        migrations.AlterField(
            model_name='plandocument',
            name='sum_assured',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='基本保额'),
        ),
        migrations.AlterField(
            model_name='plandocument',
            name='total_premium',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='总保费'),
        ),
    ]
