# Generated by Django 5.1.7 on 2025-11-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_change_premium_fields_to_bigint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信OpenID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='会话密钥')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UnionID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'wechat_users',
            },
        ),
    ]
