# Generated by Django 5.1.7 on 2025-11-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plandocument_content_wechatuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('description', models.CharField(max_length=200, verbose_name='订单描述')),
                ('transaction_id', models.CharField(blank=True, max_length=64, verbose_name='微信支付交易号')),
                ('prepay_id', models.CharField(blank=True, max_length=64, verbose_name='预支付交易会话标识')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
