# Generated by Django 5.1.7 on 2025-11-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plandocument_content_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号'),
        ),
    ]
