# Generated by Django 5.1.7 on 2025-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plandocument_content_wechatuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='summary',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='计划书概要'),
        ),
    ]
