# Generated by Django 5.1.7 on 2025-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plandocument_content_plandocument_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后处理时间'),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='processing_stage',
            field=models.CharField(choices=[('pending', '待处理'), ('extracting_basic_info', '提取基本信息中'), ('basic_info_completed', '基本信息完成'), ('extracting_table', '提取年度价值表中'), ('table_completed', '年度价值表完成'), ('extracting_summary', '提取概要中'), ('all_completed', '全部完成'), ('error', '处理出错')], default='pending', max_length=50, verbose_name='处理阶段'),
        ),
    ]
