# Generated by Django 5.1.7 on 2025-11-14 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_plandocument_content_plandocument_last_processed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(  # Already exists in database
        #     model_name='paymentorder',
        #     name='plan_type',
        #     field=models.CharField(blank=True, choices=[('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='套餐类型'),
        # ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='会员类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='到期时间')),
                ('documents_created', models.IntegerField(default=0, verbose_name='已创建计划书数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'memberships',
            },
        ),
    ]
