# Generated by Django 5.1.7 on 2025-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentorder_plan_type_plandocument_content_and_more'),
    ]

    operations = [
        # migrations.AddField(  # Already exists
        #     model_name='paymentorder',
        #     name='plan_type',
        #     field=models.CharField(blank=True, choices=[('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='套餐类型'),
        # ),
        # migrations.AddField(  # Already exists
        #     model_name='plandocument',
        #     name='content',
        #     field=models.TextField(blank=True, default='', verbose_name='识别内容'),
        # ),
        migrations.AlterField(
            model_name='membership',
            name='plan_type',
            field=models.CharField(choices=[('trial', '试用会员'), ('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='会员类型'),
        ),
    ]
