# Generated by Django 5.1.7 on 2025-11-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_plandocument_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='tablecontent',
            field=models.TextField(blank=True, default='', verbose_name='Table源代码内容'),
        ),
    ]
