# Generated by Django 5.1.7 on 2025-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_tablecontent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='tablesummary',
            field=models.TextField(blank=True, default='', verbose_name='Table概要'),
        ),
    ]
