# Generated by Django 5.1.7 on 2025-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_tablesummary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='table1',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='基本计划退保价值表'),
        ),
    ]
