# Generated by Django 5.1.7 on 2025-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_table1_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='table1',
            field=models.TextField(blank=True, default='', verbose_name='基本计划退保价值表'),
        ),
    ]
