# Generated by Django 5.1.7 on 2025-11-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_change_table1_to_longtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocument',
            name='table2',
            field=models.TextField(blank=True, default='', verbose_name='无忧选退保价值表'),
        ),
    ]
