# Generated by Django 5.2.8 on 2025-11-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_table2_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('trial', '试用会员'), ('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='套餐类型'),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='识别内容'),
        ),
        migrations.CreateModel(
            name='IPImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_url', models.CharField(blank=True, max_length=500, verbose_name='原始照片URL')),
                ('generated_image_url', models.CharField(max_length=500, verbose_name='生成的IP形象URL')),
                ('prompt', models.TextField(blank=True, verbose_name='使用的提示语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip_image', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人IP形象',
                'verbose_name_plural': '个人IP形象',
                'db_table': 'ip_images',
                'ordering': ['-updated_at'],
            },
        ),
    ]
