# Generated by Django 5.2.8 on 2025-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_paymentorder_plan_type_plandocument_content_ipimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='unionid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='UnionID'),
        ),
    ]
