# Generated by Django 5.2.8 on 2025-11-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_wechatuser_unionid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('ip_image', 'IP形象生成'), ('content_image', '文案配图生成')], max_length=20, verbose_name='生成类型')),
                ('prompt', models.TextField(blank=True, verbose_name='提示语')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_usages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Gemini调用记录',
                'verbose_name_plural': 'Gemini调用记录',
                'db_table': 'gemini_usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'generation_type', 'created_at'], name='gemini_usag_user_id_8eec71_idx'), models.Index(fields=['user', 'created_at'], name='gemini_usag_user_id_b15ec3_idx')],
            },
        ),
    ]
