# Generated by Django 5.2.8 on 2025-11-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=20, unique=True, verbose_name='套餐ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('duration', models.CharField(max_length=50, verbose_name='时长描述')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('is_popular', models.BooleanField(default=False, verbose_name='是否热门')),
                ('discount_info', models.CharField(blank=True, max_length=100, verbose_name='优惠信息')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员套餐',
                'verbose_name_plural': '会员套餐',
                'db_table': 'membership_plans',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200, verbose_name='权益描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.membershipplan', verbose_name='所属套餐')),
            ],
            options={
                'verbose_name': '套餐权益',
                'verbose_name_plural': '套餐权益',
                'db_table': 'plan_features',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
