# Generated by Django 5.2.8 on 2025-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_membershipplan_planfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(default=list, help_text='权益列表，例如：["权益1", "权益2", "权益3"]', verbose_name='权益列表'),
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
