# Generated by Django 5.2.8 on 2025-11-23 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_set_initial_quota_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='available_quota',
            field=models.IntegerField(default=3, verbose_name='可用次数'),
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('ip_image', 'IP形象'), ('content_image', '文案配图')], max_length=20, verbose_name='素材类型')),
                ('original_url', models.CharField(max_length=500, verbose_name='原始图片URL')),
                ('local_path', models.CharField(blank=True, max_length=500, verbose_name='本地存储路径')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, verbose_name='缩略图路径')),
                ('prompt', models.TextField(blank=True, verbose_name='提示语/文案')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='图片宽度')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='图片高度')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('related_ip_image_id', models.IntegerField(blank=True, null=True, verbose_name='关联的IP形象ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_library', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '素材库',
                'verbose_name_plural': '素材库',
                'db_table': 'media_library',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'media_type', 'created_at'], name='media_libra_user_id_a671c5_idx'), models.Index(fields=['user', 'is_favorite', 'created_at'], name='media_libra_user_id_121899_idx')],
            },
        ),
    ]
