# Generated by Django 5.2.8 on 2025-11-23 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_userquota_available_quota_medialibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名视频', max_length=200)),
                ('subtitles', models.TextField(blank=True)),
                ('scene_count', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=3.0)),
                ('voice', models.CharField(default='zh-CN-XiaoxiaoNeural', max_length=50)),
                ('scenes_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '视频项目',
                'verbose_name_plural': '视频项目',
                'db_table': 'video_projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
