# Generated by Django 5.2.8 on 2025-11-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_videoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='taskid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
