# Generated by Django 5.2.7 on 2025-12-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_videoproject_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例如：axa, prudential, manulife', max_length=50, unique=True, verbose_name='公司代码')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('icon', models.CharField(blank=True, help_text='Emoji图标或图片路径', max_length=50, verbose_name='图标')),
                ('color_gradient', models.CharField(blank=True, help_text='例如：from-blue-600 to-blue-700', max_length=100, verbose_name='颜色渐变')),
                ('bg_color', models.CharField(blank=True, help_text='例如：bg-blue-50', max_length=50, verbose_name='背景颜色')),
                ('description', models.TextField(blank=True, verbose_name='公司描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保险公司',
                'verbose_name_plural': '保险公司',
                'db_table': 'insurance_companies',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(help_text='例如：利益表计算、提取金额计算', max_length=100, verbose_name='请求名称')),
                ('request_url', models.CharField(help_text='完整的API端点URL', max_length=500, verbose_name='请求URL')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10, verbose_name='请求方法')),
                ('request_template', models.JSONField(default=dict, help_text='POST请求体的JSON模板', verbose_name='请求体模板')),
                ('configurable_fields', models.JSONField(default=list, help_text='用户可以修改的字段列表，例如：["premium", "withdrawalAmount", "productName"]', verbose_name='可配置字段')),
                ('field_descriptions', models.JSONField(blank=True, default=dict, help_text='字段的中文说明和默认值，例如：{"premium": {"label": "每期保费", "default": "50000", "type": "number"}}', verbose_name='字段说明')),
                ('insurance_product', models.CharField(blank=True, help_text='例如：储蓄险、重疾险、医疗险', max_length=200, verbose_name='保险品种')),
                ('description', models.TextField(blank=True, verbose_name='请求描述')),
                ('requires_bearer_token', models.BooleanField(default=False, verbose_name='需要Bearer Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to='api.insurancecompany', verbose_name='保险公司')),
            ],
            options={
                'verbose_name': '保险公司API请求',
                'verbose_name_plural': '保险公司API请求',
                'db_table': 'insurance_company_requests',
                'ordering': ['company', 'sort_order', 'request_name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='insurance_c_company_6db129_idx')],
            },
        ),
    ]
