# Generated by Django 5.2.7 on 2025-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_insurancecompany_insurancecompanyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanyrequest',
            name='response_template',
            field=models.JSONField(blank=True, default=dict, help_text='预期的响应格式示例，用于文档说明', verbose_name='响应模板'),
        ),
    ]
