# Generated by Django 5.2.7 on 2025-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_insurancecompanyrequest_response_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='bearer_token',
            field=models.TextField(blank=True, help_text='API调用所需的Bearer Token', verbose_name='Bearer Token'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='cookie',
            field=models.TextField(blank=True, help_text='API调用所需的Cookie', verbose_name='Cookie'),
        ),
    ]
