# Generated by Django 5.2.7 on 2025-12-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_insurancecompany_bearer_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanyrequest',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP请求头，例如：{"Content-Type": "application/json", "X-Custom-Header": "value"}', verbose_name='请求头'),
        ),
    ]
