# Generated by Django 5.2.7 on 2025-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_insurancecompanyrequest_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanyrequest',
            name='authorization',
            field=models.TextField(blank=True, help_text='Bearer Token或其他认证信息，例如：Bearer eyJhbGc...', verbose_name='Authorization'),
        ),
    ]
