# Generated by Django 5.2.7 on 2025-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_headers_to_insurance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='standard_surrender_policy',
            field=models.TextField(blank=True, default='', help_text='存储标准退保数据（第1-100年），JSON格式：{"standard": [{"policy_year": 1, "guaranteed": 0, "non_guaranteed": 0, "total": 0}, ...]}', verbose_name='标准退保数据'),
        ),
    ]
