# Generated by Django 5.2.7 on 2025-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_insurancecompany_standard_surrender_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji图标（如：🏦）或公司Logo的URL地址（如：https://example.com/logo.png 或 /media/logos/company.png）', max_length=200, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='standard_surrender_policy',
            field=models.TextField(blank=True, default='', help_text='存储标准退保数据（第1-100年），JSON格式：{"standard": [{"policy_year": 1, "guaranteed": 0, "non_guaranteed": 0, "total": 0, "premiums_paid": 10000}, ...]}', verbose_name='标准退保数据'),
        ),
    ]
