# Generated by Django 5.2.7 on 2025-12-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_insurancecompany_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='flagship_product',
            field=models.CharField(blank=True, default='', help_text='该保险公司的主打寿险产品名称', max_length=200, verbose_name='主打寿险产品'),
        ),
    ]
