# Generated by Django 5.2.7 on 2025-12-11 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_insurancecompany_flagship_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('payment_period', models.IntegerField(help_text='缴费年数，例如：5年、10年', verbose_name='缴费年期')),
                ('annual_premium', models.DecimalField(decimal_places=2, help_text='年缴保费金额', max_digits=15, verbose_name='年缴金额')),
                ('surrender_value_table', models.JSONField(blank=True, default=dict, help_text='JSON格式存储各年度退保价值，例如：[{"year": 1, "guaranteed": 0, "non_guaranteed": 0, "total": 0}, ...]', verbose_name='退保发还金额表')),
                ('death_benefit_table', models.JSONField(blank=True, default=dict, help_text='JSON格式存储各年度身故赔偿金额，例如：[{"year": 1, "benefit": 100000}, ...]', verbose_name='身故保险赔偿表')),
                ('is_withdrawal', models.BooleanField(default=False, help_text='是否包含提取功能', verbose_name='是否提取')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.insurancecompany', verbose_name='所属保险公司')),
            ],
            options={
                'verbose_name': '保险公司产品',
                'verbose_name_plural': '保险公司产品',
                'db_table': 'insurance_products',
                'ordering': ['company', 'sort_order', 'product_name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='insurance_p_company_2f3d80_idx')],
            },
        ),
    ]
