# Generated by Django 5.2.7 on 2025-12-11 03:32

from django.db import migrations, models
import json


def convert_json_to_text(apps, schema_editor):
    """将 JSONField 数据转换为 TextField（JSON字符串）"""
    InsuranceProduct = apps.get_model('api', 'InsuranceProduct')

    for product in InsuranceProduct.objects.all():
        # 转换 surrender_value_table
        if product.surrender_value_table:
            if not isinstance(product.surrender_value_table, str):
                product.surrender_value_table = json.dumps(
                    product.surrender_value_table,
                    ensure_ascii=False
                )
        else:
            product.surrender_value_table = ''

        # 转换 death_benefit_table
        if product.death_benefit_table:
            if not isinstance(product.death_benefit_table, str):
                product.death_benefit_table = json.dumps(
                    product.death_benefit_table,
                    ensure_ascii=False
                )
        else:
            product.death_benefit_table = ''

        product.save()


def reverse_convert(apps, schema_editor):
    """回滚：将 TextField 转换回 JSONField"""
    InsuranceProduct = apps.get_model('api', 'InsuranceProduct')

    for product in InsuranceProduct.objects.all():
        # 转换 surrender_value_table
        if product.surrender_value_table and isinstance(product.surrender_value_table, str):
            try:
                product.surrender_value_table = json.loads(product.surrender_value_table)
            except:
                product.surrender_value_table = []

        # 转换 death_benefit_table
        if product.death_benefit_table and isinstance(product.death_benefit_table, str):
            try:
                product.death_benefit_table = json.loads(product.death_benefit_table)
            except:
                product.death_benefit_table = []

        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_insuranceproduct'),
    ]

    operations = [
        # 先执行数据转换
        migrations.RunPython(convert_json_to_text, reverse_convert),
        # 再修改字段类型
        migrations.AlterField(
            model_name='insuranceproduct',
            name='death_benefit_table',
            field=models.TextField(blank=True, default='', help_text='JSON格式存储各年度身故赔偿金额，例如：[{"year": 1, "benefit": 100000}, ...]', verbose_name='身故保险赔偿表'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='surrender_value_table',
            field=models.TextField(blank=True, default='', help_text='JSON格式存储各年度退保价值，例如：[{"year": 1, "guaranteed": 0, "non_guaranteed": 0, "total": 0}, ...]', verbose_name='退保发还金额表'),
        ),
    ]
