# Generated by Django 5.2.7 on 2025-12-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_insuranceproduct_death_benefit_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe客户ID'),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe订阅ID'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('wechat', '微信支付'), ('stripe', 'Stripe支付')], default='wechat', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe支付意图ID'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe会话ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan_type',
            field=models.CharField(choices=[('trial', '试用会员'), ('solo', 'Solo计划'), ('team', 'Team计划'), ('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='会员类型'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('trial', '试用会员'), ('solo', 'Solo计划'), ('team', 'Team计划'), ('monthly', '包月会员'), ('yearly', '包年会员')], max_length=20, verbose_name='套餐类型'),
        ),
    ]
