# Generated by Django 5.2.7 on 2025-12-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_membership_stripe_customer_id_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='页面的显示名称，如：计划书分步骤分析', max_length=100, unique=True, verbose_name='页面名称')),
                ('page_code', models.CharField(help_text='页面的唯一标识，如：plan-analyzer-2', max_length=50, unique=True, verbose_name='页面代码')),
                ('route_path', models.CharField(blank=True, help_text='页面的路由路径，如：/plan-analyzer-2', max_length=200, verbose_name='路由路径')),
                ('description', models.TextField(blank=True, help_text='页面功能描述', verbose_name='描述')),
                ('require_staff', models.BooleanField(default=False, help_text='如果勾选，只有管理员（is_staff=True）可以访问', verbose_name='需要管理员权限')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此权限控制', verbose_name='启用')),
                ('icon', models.CharField(blank=True, help_text='页面图标类名', max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, help_text='页面卡片的渐变色，如：from-emerald-600 to-teal-600', max_length=100, verbose_name='颜色')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='拥有访问权限的用户组。如果为空，则所有登录用户都可以访问', to='auth.group', verbose_name='允许的用户组')),
            ],
            options={
                'verbose_name': '页面访问权限',
                'verbose_name_plural': '页面访问权限',
                'db_table': 'page_permissions',
                'ordering': ['sort_order', 'page_name'],
            },
        ),
    ]
