# Generated by Django 5.2.7 on 2025-12-14 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_pagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_product_ids', models.JSONField(default=list, help_text='用户选择的产品ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户产品对比设置',
                'verbose_name_plural': '用户产品对比设置',
            },
        ),
    ]
